### ISSUE TITLE
Unable to add to Xcode 12.4

### ISSUE THREAD

**Issue by crazyfoxkp** [ohitsdaniel/ShapeBuilder#2]
Hello, Package resolution fails when using Xcode 12.4
Is there a workaround? 

![image](https://user-images.githubusercontent.com/29047364/131270661-2720f63f-21f9-4147-998e-bb0bfa699dc9.png)

**Comment by ohitsdaniel** [comment]
Any particular reason why you're not using Xcode 12.5? As the error suggests, ShapeBuilder defines an incompatible `swift-tools-version:5.4`. 

According to [Apple's support website](https://developer.apple.com/support/xcode/), Xcode 12.4 ships with Swift 5.3, not 5.4. That's the reason why package resolution fails here.

Two possible fixes:
1) You upgrade to Xcode 12.5.
2) I drop the swift-tools-version down to 5.3.

Unless you have a reason not to upgrade your Xcode, I would prefer 1). :)

**Comment by crazyfoxkp** [comment]
Thank you for responding. 

My iMac hardware is just old enough that I cannot upgrade to BigSur/XCode 12.5. 
I'm not in a position to buy new hardware. 

If you are able to help, I'd appreciate it. 
Thanks again.

**Comment by ohitsdaniel** [comment]
Sure, I'll drop the swift toolchain version to something your Mac supports and release a new version tomorrow. :)

**Comment by ohitsdaniel** [comment]
Let me know if version 0.1.1 fixes the issue for you. :)

**Comment by crazyfoxkp** [comment]
Works for me. Thank you very much.
